const HOME_PATHNAME = '/';
const LOGIN_PATHNAME = '/login';
const REGISTER_PATHNAME = '/login';
const MANAGE_PATHNAME = '/manage';

export { LOGIN_PATHNAME, REGISTER_PATHNAME, HOME_PATHNAME, MANAGE_PATHNAME };
